# Generated by Django 2.2.10 on 2021-05-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_auto_20210505_1315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
