# Generated by Django 2.2.10 on 2021-05-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_auto_20210505_1422"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
