# Generated by Django 2.2.10 on 2021-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_auto_20210505_1449"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="answer",
            name="user_id",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
